# .github/workflows/main.yml
name: ASP.NET CI/CD

on:
  push:
    branches:
      - main # or your main branch name, e.g., master
  pull_request:
    branches:
      - main # or your main branch name, e.g., master

env:
  SOLUTION_FILE: '**/WebApplication1GIT.sln' # Adjust to your actual solution file
  WEB_PROJECT_FILE: '**/WebApplication1GIT.csproj' # Adjust to your actual web project

jobs:
  build:
    runs-on: windows-latest # Required for .NET Framework

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2 # Use this action for MSBuild

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore ${{ env.SOLUTION_FILE }}

    - name: Build
      run: |
        msbuild ${{ env.SOLUTION_FILE }} /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="${{ github.workspace }}\WebApp.zip"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-app
        path: WebApp.zip # Path to your packaged web app

    # --- CD (Continuous Deployment) considerations ---
    # For deployment to Azure App Service using GitHub Actions:
    # - name: Deploy to Azure Web App
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: '<Your-Azure-App-Service-Name>'
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Store your publish profile as a secret
    #     package: WebApp.zip
