# This workflow will build a .NET Framework project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Framework Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Define variables for your solution and web project files.
  # IMPORTANT: Replace '**/WebApplication1GIT.sln' with the CORRECT relative path
  # and exact filename of your solution file within your repository.
  # For example:
  # If your solution is at the root: 'WebApplication1GIT.sln'
  # If your solution is in a 'src' folder: 'src/WebApplication1GIT.sln'
  # If your solution is in 'src/MyProject/': 'src/MyProject/WebApplication1GIT.sln'
  SOLUTION_FILE: '**/WebApplication1GIT.sln' # <--- IMPORTANT: CORRECT THIS PATH
  WEB_PROJECT_FILE: '**/WebApplication1GIT.csproj' # <--- IMPORTANT: CORRECT THIS PATH
  BUILD_CONFIGURATION: 'Release' # Standard build configuration

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v2

    - name: Restore dependencies (NuGet)
      run: nuget restore ${{ env.SOLUTION_FILE }}

    - name: Build Web Application
      run: |
        msbuild ${{ env.SOLUTION_FILE }} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="${{ github.workspace }}\${{ github.sha }}.zip"

    - name: Test (Optional - Placeholder)
      run: echo "No automated tests configured. If you have tests, add your vstest.console.exe command here."

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-app-package
        path: ${{ github.workspace }}\${{ github.sha }}.zip
        retention-days: 7
